In [1]:
import warnings
from konlpy.tag import Okt
from collections import Counter

import numpy as np
import pandas as pd
from IPython.display import set_matplotlib_formats
warnings.filterwarnings(action='ignore')

In [2]:
data= pd.read_excel("crawl/naver_cafe_ssal_contents_2019_전처리완.xlsx")
data=data.dropna(axis=0, how='any', subset = ['content']) 
data.info()
data.reset_index(drop=True, inplace=True)
data

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9549 entries, 0 to 9553
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     9549 non-null   object
 1   nickname  9549 non-null   object
 2   date      9549 non-null   object
 3   content   9549 non-null   object
 4   comments  9032 non-null   object
dtypes: object(5)
memory usage: 447.6+ KB

,title,nickname,date,content,comments
0,다운타운 **름 썩은곰팡이 쌀 ..,taniamama,2019.01.30,"안녕하세요,,18개월 아기 기르는 엄마입니다..이럴땐 어떻게 대처 해야할지 모르겠어...",요즘 여기 쌀 할인하던데 같은쌀일까요||전 2018년 10월에 풍 * 햅쌀 이라고 ...
1,"쌀마들렌 3종(모카, 허니유자, 쑥)",쪼로밋,2019.01.08,엄청 오랜만에 베이킹 하는거 같네용..ㅠㅠ버터도 거의바닥이었고..가루류도 없는데다가...,쑥 마들렌!! 완전 맛나겠다용~~~쑥향 솔솔~~😍||콩가루 묻힐까하다가 깔끔한게 나...
2,쌀에 넣어놓은 숯에 벌레가 ㅠ,연슈,2019.01.17,벌레얘기 죄송해요 ㅠ쌀을 상온 보관 중인데(냉장고에 도저히 자리가 안나서)혹시나 쌀...,"숯, 마늘 넣어두면 벌레 안 생기다는 말 들었는데\n생기는군요 ㅠㅠ\n전 겨울엔 락..."
3,"67,000 원짜리 쌀 개봉했습니다!",박지마미,2019.01.14,오늘 저희 집 쌀이 없어서 2식은 분식으로 떼웠는데남편이가 쌀을 사오긴 사왔는데매대...,악..비싸네요ㅠ\n그만큼 더 찰지고 맛있을꺼예요~ ㅎㅎ\n\n근데 저도 실한올잡아서...
4,첨으로 베트남쌀로 밥지었어요.,조은사람,2019.01.26,처음와서는 일본품종쌀 주문해먹었었고.그담엔 한국쌀먹었는데~마트에서 한국아주머니께서 ...,저도 베트남쌀 사먹어요~~생각보다 맛있더라구요~~||그니까요. 맛도없고 냄새도날줄...
...,...,...,...,...,...
9544,[거제수월자이점] 오늘의 간식은 쌀과자,거제수월자이점,2019.12.17,쌀과자 냠냠 맛있게 먹으며 열심히 즐겁게 공부해봐요~💕,||
9545,40mm매일 분유스푼으로 쌀가루 몇그램 나올까요?,새로운시작,2019.12.13,저울은 준비를 안했어요분유스푼으로 쌀가루 몇그램 나올까요?초기이유식입니다,혹시분유통있으신가요? 1스푼에 몇그램이라고써져있는데... 저50ml분유스푼쓰는데 그...
9546,잊고 있었던 티몬 쌀,부산무진,2019.12.24,*오늘의 최저가 정보롯데 백화점 납품 10kg 쌀등급 상두개 구매 개당 23.7...,장사두안되고 ~\n손님도 없고~~\n심심해요 ㅡㅡ;;;||장사도 안되고 \n손님도 ...
9547,"돌전후 아기신발(완료) , 쌀튀밥(완료) 드림 ^^",장군맘 ㅋ,2019.12.15,쌀튀밥 두개 (유통기한 2020.3.17)어그 130사이즈(사용감 잇네용)검정 운동...,쌀튀밥 받고시퍼요||네 챗드릴게요 ㅋ||운동화 120받고싶어요||네 챗드릴게요||혹...
9548,맘마밀 이유식 5개.퓨레 4개. 쌀과자1봉,린n은v83v둔덕,2019.12.01,맘마밀 안심이유식 단호박과 소고기 5개사과와 고구마 퓨레 4개 (20년 5월까지)요...,NaN

In [3]:
data2=data.copy()

In [4]:
for i in range(len(data2)):
    data2["content"][i]=str(data2["content"][i]).replace('네요','네요||-||').replace('하죠','하죠||-||').replace('데요','데요||-||').replace('이네요','이네요||-||').replace('네요.','네요||-||').replace('되죠','되죠||-||').replace('대요','대요||-||').replace('이요','이요||-||').replace('돼요.','돼요||-||').replace('되요','되요||-||').replace('다닙니다','다닙니다||-||').replace('입니다','입니다||-||').replace('입니다.','입니다||-||').replace('니다','니다||-||').replace('중입니다','중입니다||-||').replace('입니다','입니다||-||').replace('나요.','나요||-||').replace('어요','어요||-||').replace('까요','까요||-||').replace('에요','에요||-||').replace('이에요','이에요||-||').replace('봐요','봐요||-||').replace('아요.','아요||-||').replace('해요','해요||-||').replace('려요','려요||-||').replace('구요','구요||-||').replace('고요','고요||-||').replace('죠','죠||-||').replace(':)','').replace('더라','더라||-||').replace('게요','게요||-||').replace('께요','께요||-||').replace('세요','세요||-||').replace('든요','든요||-||').replace('예요','예요||-||').replace('서요','서요||-||')

In [5]:
for i in range(len(data2)):
    data2["content"][i]=str(data2["content"][i]).replace('.','').replace('?','').replace('~','').replace('!','').replace('^','').replace('#','').replace('★','').replace('ㅋ','').replace('ㅜ','').replace('ㅠ','').replace('ㅎ','').replace('ㅏ','').replace('ㅡ','')

In [6]:
data2

,title,nickname,date,content,comments
0,다운타운 **름 썩은곰팡이 쌀 ..,taniamama,2019.01.30,"안녕하세요||-||,,18개월 아기 기르는 엄마입니다||-||||-||||-||이럴...",요즘 여기 쌀 할인하던데 같은쌀일까요||전 2018년 10월에 풍 * 햅쌀 이라고 ...
1,"쌀마들렌 3종(모카, 허니유자, 쑥)",쪼로밋,2019.01.08,엄청 오랜만에 베이킹 하는거 같네용버터도 거의바닥이었고가루류도 없는데다가저번주부터 ...,쑥 마들렌!! 완전 맛나겠다용~~~쑥향 솔솔~~😍||콩가루 묻힐까하다가 깔끔한게 나...
2,쌀에 넣어놓은 숯에 벌레가 ㅠ,연슈,2019.01.17,벌레얘기 죄송해요||-|| 쌀을 상온 보관 중인데(냉장고에 도저히 자리가 안나서)혹...,"숯, 마늘 넣어두면 벌레 안 생기다는 말 들었는데\n생기는군요 ㅠㅠ\n전 겨울엔 락..."
3,"67,000 원짜리 쌀 개봉했습니다!",박지마미,2019.01.14,오늘 저희 집 쌀이 없어서 2식은 분식으로 떼웠는데남편이가 쌀을 사오긴 사왔는데매대...,악..비싸네요ㅠ\n그만큼 더 찰지고 맛있을꺼예요~ ㅎㅎ\n\n근데 저도 실한올잡아서...
4,첨으로 베트남쌀로 밥지었어요.,조은사람,2019.01.26,처음와서는 일본품종쌀 주문해먹었었고그담엔 한국쌀먹었는데마트에서 한국아주머니께서 현지...,저도 베트남쌀 사먹어요~~생각보다 맛있더라구요~~||그니까요. 맛도없고 냄새도날줄...
...,...,...,...,...,...
9544,[거제수월자이점] 오늘의 간식은 쌀과자,거제수월자이점,2019.12.17,쌀과자 냠냠 맛있게 먹으며 열심히 즐겁게 공부해봐요||-||💕,||
9545,40mm매일 분유스푼으로 쌀가루 몇그램 나올까요?,새로운시작,2019.12.13,저울은 준비를 안했어요||-||분유스푼으로 쌀가루 몇그램 나올까요||-||초기이유식...,혹시분유통있으신가요? 1스푼에 몇그램이라고써져있는데... 저50ml분유스푼쓰는데 그...
9546,잊고 있었던 티몬 쌀,부산무진,2019.12.24,*오늘의 최저가 정보롯데 백화점 납품 10kg 쌀등급 상두개 구매 개당 2370...,장사두안되고 ~\n손님도 없고~~\n심심해요 ㅡㅡ;;;||장사도 안되고 \n손님도 ...
9547,"돌전후 아기신발(완료) , 쌀튀밥(완료) 드림 ^^",장군맘 ㅋ,2019.12.15,쌀튀밥 두개 (유통기한 2020317)어그 130사이즈(사용감 잇네용)검정 운동화 ...,쌀튀밥 받고시퍼요||네 챗드릴게요 ㅋ||운동화 120받고싶어요||네 챗드릴게요||혹...
9548,맘마밀 이유식 5개.퓨레 4개. 쌀과자1봉,린n은v83v둔덕,2019.12.01,맘마밀 안심이유식 단호박과 소고기 5개사과와 고구마 퓨레 4개 (20년 5월까지)요...,NaN

In [7]:
conlist=[]
for i in range(len(data2)):

    a=[]
    a.append(data2["content"][i].split("||-||"))
    
    d=pd.DataFrame(a).T
    d=d[d[0]!=""].reset_index()
    d=d[d[0]!="구요"].reset_index()
    conca1=d[d[0].str.contains("이유식|아이|아기|애기|아가|미음|분유",na=False)]
    conidex=conca1.index
    list(conidex)


    for i in list(conidex):
        try:

             conlist.append(str(d[0][i-1])+" "+str(d[0][i])+" "+str(d[0][i+1]))

        except:
            try:
                conlist.append(str(d[0][i])+" "+str(d[0][i+1]))
            except:
                try:
                    conlist.append(str(d[0][i-1])+" "+str(d[0][i]))
                except:
                    conlist.append(str(d[0][i]))

In [8]:
aaaa=pd.DataFrame(conlist)
aaaa

                                                      0
0     안녕하세요 ,,18개월 아기 기르는 엄마입니다 이럴땐 어떻게 대처 해야할지 모르겠어...
1     이걸 지금까지 먹은거야 싶어**름 에 전화넣으니커스터머 서비스 전화받으신 분이 사과...
2      하니아기먹는쌀은 조금더 좋은거사먹이라며경기미를 추천해주시는데경기미 돌이 가끔 나와...
3     첫째가 엄마 맛있는 냄새가 엄청나요하면서 먹어줘서 그저 또 행복해졌었다는퍽퍽할까봐 ...
4     , 저희 엄마께 여쭤보니 무슨쌀인지는 모르겠다고포장지도 버렸다고 단지 생협에서 사셨...
...                                                 ...
4186  이제 다른 재료 섞으려고하는데요 힙 이유식을 선물 받았어요  보니까 브로콜리, 당근...
4187  충주愛 퐁당 농촌체험여행 발효쌀찐빵만들기191130191201충주농촌체험여행쌀찐빵만...
4188          저울은 준비를 안했어요 분유스푼으로 쌀가루 몇그램 나올까요 초기이유식입니다
4189                       분유스푼으로 쌀가루 몇그램 나올까요 초기이유식입니다
4190  맘마밀 안심이유식 단호박과 소고기 5개사과와 고구마 퓨레 4개 (20년 5월까지)요...

[4191 rows x 1 columns]

In [9]:
for i in range(len(aaaa)):
    aaaa[0][i]=aaaa[0][i].lstrip()
    aaaa[0][i]=aaaa[0][i].rstrip()

In [12]:
qw=aaaa.drop_duplicates([0],keep = 'first')
qw.to_excel("ba2.xlsx")
qw

                                                      0
0     안녕하세요 ,,18개월 아기 기르는 엄마입니다 이럴땐 어떻게 대처 해야할지 모르겠어...
1     이걸 지금까지 먹은거야 싶어**름 에 전화넣으니커스터머 서비스 전화받으신 분이 사과...
2     하니아기먹는쌀은 조금더 좋은거사먹이라며경기미를 추천해주시는데경기미 돌이 가끔 나와 ...
3     첫째가 엄마 맛있는 냄새가 엄청나요하면서 먹어줘서 그저 또 행복해졌었다는퍽퍽할까봐 ...
4     , 저희 엄마께 여쭤보니 무슨쌀인지는 모르겠다고포장지도 버렸다고 단지 생협에서 사셨...
...                                                 ...
4185      이유식 초기로 쌀가루 받은거로 10일 정도 했어요 이제 다른 재료 섞으려고하는데요
4186  이제 다른 재료 섞으려고하는데요 힙 이유식을 선물 받았어요  보니까 브로콜리, 당근...
4187  충주愛 퐁당 농촌체험여행 발효쌀찐빵만들기191130191201충주농촌체험여행쌀찐빵만...
4188          저울은 준비를 안했어요 분유스푼으로 쌀가루 몇그램 나올까요 초기이유식입니다
4189                       분유스푼으로 쌀가루 몇그램 나올까요 초기이유식입니다

[4056 rows x 1 columns]

In [13]:
conlist=[]
for i in range(len(data2)):

    a=[]
    a.append(data2["content"][i].split("||-||"))
    
    d=pd.DataFrame(a).T
    d=d[d[0]!=""].reset_index()
    d=d[d[0]!="구요"].reset_index()
    conca1=d[d[0].str.contains("밥|아침|저녁|집밥",na=False)]
    conidex=conca1.index
    list(conidex)


    for i in list(conidex):
        try:

             conlist.append(str(d[0][i-1])+" "+str(d[0][i])+" "+str(d[0][i+1]))

        except:
            try:
                conlist.append(str(d[0][i])+" "+str(d[0][i+1]))
            except:
                try:
                    conlist.append(str(d[0][i-1])+" "+str(d[0][i]))
                except:
                    conlist.append(str(d[0][i]))

In [14]:
bbbb=pd.DataFrame(conlist)
bbbb

                                                      0
0     이럴땐 어떻게 대처 해야할지 모르겠어서 올려봐요 보통 6개월에 한번 사던쌀이 아들이...
1     쌀을 뜯고 얼마도지않아 쌀을 씻을때 부서지는 현상이 자주일어나더니3/1쯤 먹으니 누...
2     그래서 아기랑 가지고 갔어요  **름 에 앞면있는분들이 조금 계셔서 그전에 쥐파먹은...
3     앞으로 마들렌은 쌀가루로 하는걸로 결정내일부터 다시 애기들 어린이집 가는데벌써 행복...
4      쌀을 상온 보관 중인데(냉장고에 도저히 자리가 안나서)혹시나 쌀벌레 생길까봐 마늘...
...                                                 ...
2946  벼에서 쌀로, 다시 밥과 막걸리로 … 사라진 1500종, 토종 벼의 귀환을 꿈꾸다 ...
2947   약 1만5000년 전 것으로, 중국보다 4000년 앞서는 것으로 분석됐죠  한반도...
2948   20키로에 55000원이라고합니다  밥을하면 주위사람들이 맛있다고 한다네요 혹 필...
2949   불린쌀로 먼저 찌고 갈으래는데 어른들 해먹으려고 쌀밥 해노은거를 바로 갈아도 상관없나요
2950  쌀튀밥 두개 (유통기한 2020317)어그 130사이즈(사용감 잇네용)검정 운동화 ...

[2951 rows x 1 columns]

In [15]:
for i in range(len(bbbb)):
    bbbb[0][i]=bbbb[0][i].lstrip()
    bbbb[0][i]=bbbb[0][i].rstrip()

In [16]:
hs=bbbb.drop_duplicates([0],keep = 'first')
hs.to_excel("hs2.xlsx")
hs

                                                      0
0     이럴땐 어떻게 대처 해야할지 모르겠어서 올려봐요 보통 6개월에 한번 사던쌀이 아들이...
1     쌀을 뜯고 얼마도지않아 쌀을 씻을때 부서지는 현상이 자주일어나더니3/1쯤 먹으니 누...
2     그래서 아기랑 가지고 갔어요  **름 에 앞면있는분들이 조금 계셔서 그전에 쥐파먹은...
3     앞으로 마들렌은 쌀가루로 하는걸로 결정내일부터 다시 애기들 어린이집 가는데벌써 행복...
4     쌀을 상온 보관 중인데(냉장고에 도저히 자리가 안나서)혹시나 쌀벌레 생길까봐 마늘 ...
...                                                 ...
2946  벼에서 쌀로, 다시 밥과 막걸리로 … 사라진 1500종, 토종 벼의 귀환을 꿈꾸다 ...
2947  약 1만5000년 전 것으로, 중국보다 4000년 앞서는 것으로 분석됐죠  한반도에...
2948  20키로에 55000원이라고합니다  밥을하면 주위사람들이 맛있다고 한다네요 혹 필요...
2949   불린쌀로 먼저 찌고 갈으래는데 어른들 해먹으려고 쌀밥 해노은거를 바로 갈아도 상관없나요
2950  쌀튀밥 두개 (유통기한 2020317)어그 130사이즈(사용감 잇네용)검정 운동화 ...

[2913 rows x 1 columns]

In [17]:
conlist=[]
for i in range(len(data2)):

    a=[]
    a.append(data2["content"][i].split("||-||"))
    
    d=pd.DataFrame(a).T
    d=d[d[0]!=""].reset_index()
    d=d[d[0]!="구요"].reset_index()
    conca1=d[d[0].str.contains("과자|가루|떡|반죽|튀밥|밀가루|설탕|식빵|쿠키|카스테라|우유|빵|케이크|초코|베이킹|반죽|버터|크림|디저트",na=False)]
    conidex=conca1.index
    list(conidex)


    for i in list(conidex):
        try:

             conlist.append(str(d[0][i-1])+" "+str(d[0][i])+" "+str(d[0][i+1]))

        except:
            try:
                conlist.append(str(d[0][i])+" "+str(d[0][i+1]))
            except:
                try:
                    conlist.append(str(d[0][i-1])+" "+str(d[0][i]))
                except:
                    conlist.append(str(d[0][i]))

In [18]:
cccc=pd.DataFrame(conlist)
cccc

                                                      0
0     엄청 오랜만에 베이킹 하는거 같네용버터도 거의바닥이었고가루류도 없는데다가저번주부터 ...
1     오늘까지 아무것도 안하믄제가 너무 피폐해질거같아서보내드려야 할분도 계시구(물속에비친...
2     흑나눔 보내드리기로한거 이번주에 꼭 보내께여)박력분은없고마들렌은 굽고싶고 해서박력쌀...
3     마들렌도 첨인데쌀가루로 하려니 걱정이 앞섰지만맛없으면 내가먹겠다 하는 마음으로모카,...
4     )마지막판 구울때야 온도감잡아서제대로 배꼽이 올라온건 한판밖에 안되네요 첫째가 엄마...
...                                                 ...
7752   일단 아시겠지만 그런 과자는 크기가 커서 사 들고 다니기 부담스럽고 여러 이유 때...
7753                     쌀과자 냠냠 맛있게 먹으며 열심히 즐겁게 공부해봐요 💕
7754          저울은 준비를 안했어요 분유스푼으로 쌀가루 몇그램 나올까요 초기이유식입니다
7755  쌀튀밥 두개 (유통기한 2020317)어그 130사이즈(사용감 잇네용)검정 운동화 ...
7756  맘마밀 안심이유식 단호박과 소고기 5개사과와 고구마 퓨레 4개 (20년 5월까지)요...

[7757 rows x 1 columns]

In [19]:
for i in range(len(cccc)):
    cccc[0][i]=cccc[0][i].lstrip()
    cccc[0][i]=cccc[0][i].rstrip()

In [20]:
dst=cccc.drop_duplicates([0],keep = 'first')
dst.to_excel("dst2.xlsx")
dst

                                                      0
0     엄청 오랜만에 베이킹 하는거 같네용버터도 거의바닥이었고가루류도 없는데다가저번주부터 ...
1     오늘까지 아무것도 안하믄제가 너무 피폐해질거같아서보내드려야 할분도 계시구(물속에비친...
2     흑나눔 보내드리기로한거 이번주에 꼭 보내께여)박력분은없고마들렌은 굽고싶고 해서박력쌀...
3     마들렌도 첨인데쌀가루로 하려니 걱정이 앞섰지만맛없으면 내가먹겠다 하는 마음으로모카,...
4     )마지막판 구울때야 온도감잡아서제대로 배꼽이 올라온건 한판밖에 안되네요 첫째가 엄마...
...                                                 ...
7751  사실 평소에 전 과자를 별로 안먹구 초콜릿이나 젤리같은 걸 먹는 거 같아여 과자 먹...
7752  일단 아시겠지만 그런 과자는 크기가 커서 사 들고 다니기 부담스럽고 여러 이유 때문...
7753                     쌀과자 냠냠 맛있게 먹으며 열심히 즐겁게 공부해봐요 💕
7754          저울은 준비를 안했어요 분유스푼으로 쌀가루 몇그램 나올까요 초기이유식입니다
7755  쌀튀밥 두개 (유통기한 2020317)어그 130사이즈(사용감 잇네용)검정 운동화 ...

[7490 rows x 1 columns]

In [21]:
conlist=[]
for i in range(len(data2)):

    a=[]
    a.append(data2["content"][i].split("||-||"))
    
    d=pd.DataFrame(a).T
    d=d[d[0]!=""].reset_index()
    d=d[d[0]!="구요"].reset_index()
    conca1=d[d[0].str.contains("치킨|통닭|떡볶이|피자|핫도그|막걸리|간식|수업|만들기|죽|후라이드|파스타|강정|튀김|면|레시피|소금|치즈|음식|소고기|메뉴|야채|고구마|감자|양념|단호박|물",na=False)]
    conidex=conca1.index
    list(conidex)


    for i in list(conidex):
        try:

             conlist.append(str(d[0][i-1])+" "+str(d[0][i])+" "+str(d[0][i+1]))

        except:
            try:
                conlist.append(str(d[0][i])+" "+str(d[0][i+1]))
            except:
                try:
                    conlist.append(str(d[0][i-1])+" "+str(d[0][i]))
                except:
                    conlist.append(str(d[0][i]))

In [22]:
dddd=pd.DataFrame(conlist)
dddd

                                                      0
0     이럴땐 어떻게 대처 해야할지 모르겠어서 올려봐요 보통 6개월에 한번 사던쌀이 아들이...
1     그래서 아기랑 가지고 갔어요  **름 에 앞면있는분들이 조금 계셔서 그전에 쥐파먹은...
2     슬슬 열이 받는데 그 남자분 저보고 그럼 나머지 쌀은 어딨냐며 묻네요 황당하여라기분...
3     무슨 고객대응은 그렇게하는지한심하더라  왠만하면 아줌마는 진상이다 소리들을까 그동안...
4     어제는 tv도 뽀사버린 비글 두마리첫째 늦은 기저귀 뗀다고 이불빨래에 아주 기절하기...
...                                                 ...
8727  충주愛 퐁당 농촌체험여행 발효쌀찐빵만들기191130191201충주농촌체험여행쌀찐빵만...
8728  이제 후기 시작 하는데여태까지 백미만 먹여본 게으른 엄마예요 후기 시작하면서 이제 ...
8729   사실 평소에 전 과자를 별로 안먹구 초콜릿이나 젤리같은 걸 먹는 거 같아여 과자 ...
8730  여기 상품 올려 주시는분이랑 판매자랑은 아무연관이 없습니다 제품및 배송 문제점에 대...
8731  맘마밀 안심이유식 단호박과 소고기 5개사과와 고구마 퓨레 4개 (20년 5월까지)요...

[8732 rows x 1 columns]

In [23]:
for i in range(len(dddd)):
    dddd[0][i]=dddd[0][i].lstrip()
    dddd[0][i]=dddd[0][i].rstrip()

In [24]:
rcp=dddd.drop_duplicates([0],keep = 'first')
rcp.to_excel("rcp2.xlsx")
rcp

                                                      0
0     이럴땐 어떻게 대처 해야할지 모르겠어서 올려봐요 보통 6개월에 한번 사던쌀이 아들이...
1     그래서 아기랑 가지고 갔어요  **름 에 앞면있는분들이 조금 계셔서 그전에 쥐파먹은...
2     슬슬 열이 받는데 그 남자분 저보고 그럼 나머지 쌀은 어딨냐며 묻네요 황당하여라기분...
3     무슨 고객대응은 그렇게하는지한심하더라  왠만하면 아줌마는 진상이다 소리들을까 그동안...
4     어제는 tv도 뽀사버린 비글 두마리첫째 늦은 기저귀 뗀다고 이불빨래에 아주 기절하기...
...                                                 ...
8726  보니까 브로콜리, 당근, 무우, 소고기 종류 다양한데 이걸로 시작해도 될까요  아니...
8727  충주愛 퐁당 농촌체험여행 발효쌀찐빵만들기191130191201충주농촌체험여행쌀찐빵만...
8728  이제 후기 시작 하는데여태까지 백미만 먹여본 게으른 엄마예요 후기 시작하면서 이제 ...
8729  사실 평소에 전 과자를 별로 안먹구 초콜릿이나 젤리같은 걸 먹는 거 같아여 과자 먹...
8730  여기 상품 올려 주시는분이랑 판매자랑은 아무연관이 없습니다 제품및 배송 문제점에 대...

[8539 rows x 1 columns]

In [26]:
conlist=[]
for i in range(len(data2)):

    a=[]
    a.append(data2["content"][i].split("||-||"))
    
    d=pd.DataFrame(a).T
    d=d[d[0]!=""].reset_index()
    d=d[d[0]!="구요"].reset_index()
    conca1=d[d[0].str.contains("보관|박스|벌레|곰팡이|벌래|바구미",na=False)]
    conidex=conca1.index
    list(conidex)


    for i in list(conidex):
        try:

             conlist.append(str(d[0][i-1])+" "+str(d[0][i])+" "+str(d[0][i+1]))

        except:
            try:
                conlist.append(str(d[0][i])+" "+str(d[0][i+1]))
            except:
                try:
                    conlist.append(str(d[0][i-1])+" "+str(d[0][i]))
                except:
                    conlist.append(str(d[0][i]))

In [27]:
eeee=pd.DataFrame(conlist)
eeee

                                                      0
0     보통 6개월에 한번 사던쌀이 아들이 같이 밥을 먹기 시작하면서 3개월에 한번 삽니다...
1     그때만해도 대수롭지 않게 골라내고 밥을 했었는데 이제 거진 쌀을 다 먹어갈때쯤 오늘...
2     쌀이 쌀봉지 바닥에 어른 손바닥 보다 크게 눌러붙어 곰팡이가 생겨있고 그동안 봐왔던...
3     그래서 아기랑 가지고 갔어요  **름 에 앞면있는분들이 조금 계셔서 그전에 쥐파먹은...
4     벌레얘기 죄송해요  쌀을 상온 보관 중인데(냉장고에 도저히 자리가 안나서)혹시나 쌀...
...                                                 ...
1759                                쌀이 벌레먹었어요 필요하신분 있나요
1760  친정해서 보내온 2019 햅쌀  판매해요 너무많이 보내셔서 ;; 보관도 힘들어서요 ...
1761                           벌레먹은쌀 일년반되었구요 필요하신분 드립니다
1762  ”      보안여관 안으로 들어가니 토종 벼에서 영감을 받은 작품들이 펼쳐진다 송...
1763  쌀벌레 있는 쌀 어케 하시나요 15키로 정도 되는데자꾸 남편은 몇마리 있으니 걍 괜...

[1764 rows x 1 columns]

In [28]:
for i in range(len(eeee)):
    eeee[0][i]=eeee[0][i].lstrip()
    eeee[0][i]=eeee[0][i].rstrip()

In [29]:
bug=eeee.drop_duplicates([0],keep = 'first')
bug.to_excel("bug2.xlsx")
bug

                                                      0
0     보통 6개월에 한번 사던쌀이 아들이 같이 밥을 먹기 시작하면서 3개월에 한번 삽니다...
1     그때만해도 대수롭지 않게 골라내고 밥을 했었는데 이제 거진 쌀을 다 먹어갈때쯤 오늘...
2     쌀이 쌀봉지 바닥에 어른 손바닥 보다 크게 눌러붙어 곰팡이가 생겨있고 그동안 봐왔던...
3     그래서 아기랑 가지고 갔어요  **름 에 앞면있는분들이 조금 계셔서 그전에 쥐파먹은...
4     벌레얘기 죄송해요  쌀을 상온 보관 중인데(냉장고에 도저히 자리가 안나서)혹시나 쌀...
...                                                 ...
1759                                쌀이 벌레먹었어요 필요하신분 있나요
1760  친정해서 보내온 2019 햅쌀  판매해요 너무많이 보내셔서 ;; 보관도 힘들어서요 ...
1761                           벌레먹은쌀 일년반되었구요 필요하신분 드립니다
1762  ”      보안여관 안으로 들어가니 토종 벼에서 영감을 받은 작품들이 펼쳐진다 송...
1763  쌀벌레 있는 쌀 어케 하시나요 15키로 정도 되는데자꾸 남편은 몇마리 있으니 걍 괜...

[1714 rows x 1 columns]

In [30]:
conlist=[]
for i in range(len(data2)):

    a=[]
    a.append(data2["content"][i].split("||-||"))
    
    d=pd.DataFrame(a).T
    d=d[d[0]!=""].reset_index()
    d=d[d[0]!="구요"].reset_index()
    conca1=d[d[0].str.contains("곤약|유기농|다이어트|건강",na=False)]
    conidex=conca1.index
    list(conidex)


    for i in list(conidex):
        try:

             conlist.append(str(d[0][i-1])+" "+str(d[0][i])+" "+str(d[0][i+1]))

        except:
            try:
                conlist.append(str(d[0][i])+" "+str(d[0][i+1]))
            except:
                try:
                    conlist.append(str(d[0][i-1])+" "+str(d[0][i]))
                except:
                    conlist.append(str(d[0][i]))

In [31]:
ffff=pd.DataFrame(conlist)
ffff

                                                     0
0     단엄마도 같이 살이 찔수있어요  저 어제부터 다이어트시작인데ps 혹시 광고성 글인...
1    작년 추석때 받은 유기농 쌀 2키로 짜리가 3개 총 6키로가 있습니다 평소 시골에서...
2    평소 시골에서 보내주시는 쌀이 따로 있어서 먹지 못하고시간이 흘렀어요  사진에서 보...
3    아이들 방학이 다가오네요 방학때 이렇게 놀면 건강에 좋은 간식도생기고 좋을듯 해서올...
4    밥 잘 안 먹는 아이라쌀이 달라진다고 식욕이 폭발하진 않겠지만먹어보신 쌀 중에 맛난...
..                                                 ...
854  오아시스에서 2019년 유기농 햅쌀 구매했는데 상태가 너무 안좋아요  애기 못먹일거...
855     애기 못먹일거 같아요  애기 이유식 만들 유기농쌀 어디서 구매하세요 어디가 좋은가요
856               올가 유기농 쌀가루 9개 들어있어요 빨리 오실수 있는 분 드릴께요
857               유기농쌀 4키로정도랑찹쌀 3키로정도 있는데혹시 필요하신분 계실까요
858  맘마밀 안심이유식 단호박과 소고기 5개사과와 고구마 퓨레 4개 (20년 5월까지)요...

[859 rows x 1 columns]

In [32]:
for i in range(len(ffff)):
    ffff[0][i]=ffff[0][i].lstrip()
    ffff[0][i]=ffff[0][i].rstrip()

In [33]:
hth=ffff.drop_duplicates([0],keep = 'first')
hth.to_excel("hth2.xlsx")
hth

                                                     0
0    단엄마도 같이 살이 찔수있어요  저 어제부터 다이어트시작인데ps 혹시 광고성 글인가...
1    작년 추석때 받은 유기농 쌀 2키로 짜리가 3개 총 6키로가 있습니다 평소 시골에서...
2    평소 시골에서 보내주시는 쌀이 따로 있어서 먹지 못하고시간이 흘렀어요  사진에서 보...
3    아이들 방학이 다가오네요 방학때 이렇게 놀면 건강에 좋은 간식도생기고 좋을듯 해서올...
4    밥 잘 안 먹는 아이라쌀이 달라진다고 식욕이 폭발하진 않겠지만먹어보신 쌀 중에 맛난...
..                                                 ...
853  진강정 오란다강정  많이들 사랑해 주시는데 개인적으로 오란다강정을 위협할 정도로 맛...
854  오아시스에서 2019년 유기농 햅쌀 구매했는데 상태가 너무 안좋아요  애기 못먹일거...
855     애기 못먹일거 같아요  애기 이유식 만들 유기농쌀 어디서 구매하세요 어디가 좋은가요
856               올가 유기농 쌀가루 9개 들어있어요 빨리 오실수 있는 분 드릴께요
857               유기농쌀 4키로정도랑찹쌀 3키로정도 있는데혹시 필요하신분 계실까요

[846 rows x 1 columns]

In [34]:
conlist=[]
for i in range(len(data2)):

    a=[]
    a.append(data2["content"][i].split("||-||"))
    
    d=pd.DataFrame(a).T
    d=d[d[0]!=""].reset_index()
    d=d[d[0]!="구요"].reset_index()
    conca1=d[d[0].str.contains("가격|비싸|싸",na=False)]
    conidex=conca1.index
    list(conidex)


    for i in list(conidex):
        try:

             conlist.append(str(d[0][i-1])+" "+str(d[0][i])+" "+str(d[0][i+1]))

        except:
            try:
                conlist.append(str(d[0][i])+" "+str(d[0][i+1]))
            except:
                try:
                    conlist.append(str(d[0][i-1])+" "+str(d[0][i]))
                except:
                    conlist.append(str(d[0][i]))

In [35]:
gggg=pd.DataFrame(conlist)
gggg

                                                     0
0     옥수수쌀식빵, 블루베리쌀식빵, 흑미쌀식빵, 홍국쌀식빵, 밤식빵 등등매일 다른 식빵...
1    사진에는 잘 안보이는데 시골에서 보내주신 쌀 두 포대 오늘 뜯어보니 다 현미처럼 누...
2    원리는 엄청 간단한데(그냥 하얀 돌기로 박박 씻고 연두색 체 있는 쪽으로 물 빼면 ...
3    no frills &superstore 동시에 botan rice 8kg 세일하니 ...
4    쌀카스테라 로 전하는 부담없는 명절선물 일석다중이 입니다  노른자 많이 써서 좋고쌀...
..                                                 ...
747  케잌먹고싶을때, 당땡길때 있잖아요 근데 일반빵집껀 크거나 비싸서 망설이는데 엉뚱마마...
748   연말 불우이웃 돕기로 쌀을 기증하려는데 10kg 가격 아시는분있나요  ======...
749   품종은 추청('아키바리')입니다 가격은 6만원이구요 서울 전 지역은 무료로 배송 ...
750    *오늘의 최저가 정보롯데 백화점 납품 10kg 쌀등급 상두개 구매 개당 2370...
751    *오늘의 최저가 정보롯데 백화점 납품 10kg 쌀등급 상두개 구매 개당 2370...

[752 rows x 1 columns]

In [36]:
for i in range(len(gggg)):
    gggg[0][i]=gggg[0][i].lstrip()
    gggg[0][i]=gggg[0][i].rstrip()

In [37]:
prc=gggg.drop_duplicates([0],keep = 'first')
prc.to_excel("prc2.xlsx")
prc

                                                     0
0    옥수수쌀식빵, 블루베리쌀식빵, 흑미쌀식빵, 홍국쌀식빵, 밤식빵 등등매일 다른 식빵들...
1    사진에는 잘 안보이는데 시골에서 보내주신 쌀 두 포대 오늘 뜯어보니 다 현미처럼 누...
2    원리는 엄청 간단한데(그냥 하얀 돌기로 박박 씻고 연두색 체 있는 쪽으로 물 빼면 ...
3    no frills &superstore 동시에 botan rice 8kg 세일하니 ...
4    쌀카스테라 로 전하는 부담없는 명절선물 일석다중이 입니다  노른자 많이 써서 좋고쌀...
..                                                 ...
747  케잌먹고싶을때, 당땡길때 있잖아요 근데 일반빵집껀 크거나 비싸서 망설이는데 엉뚱마마...
748  연말 불우이웃 돕기로 쌀을 기증하려는데 10kg 가격 아시는분있나요  =======...
749  품종은 추청('아키바리')입니다 가격은 6만원이구요 서울 전 지역은 무료로 배송 해...
750  *오늘의 최저가 정보롯데 백화점 납품 10kg 쌀등급 상두개 구매 개당 23700원...
751  *오늘의 최저가 정보롯데 백화점 납품 10kg 쌀등급 상두개 구매 개당 23700원...

[746 rows x 1 columns]

In [38]:
conlist=[]
for i in range(len(data2)):

    a=[]
    a.append(data2["content"][i].split("||-||"))
    
    d=pd.DataFrame(a).T
    d=d[d[0]!=""].reset_index()
    d=d[d[0]!="구요"].reset_index()
    conca1=d[d[0].str.contains("느낌|냄새|식감|맛|밥맛|향|양|기한|유통기한|도정",na=False)]
    conidex=conca1.index
    list(conidex)


    for i in list(conidex):
        try:

             conlist.append(str(d[0][i-1])+" "+str(d[0][i])+" "+str(d[0][i+1]))

        except:
            try:
                conlist.append(str(d[0][i])+" "+str(d[0][i+1]))
            except:
                try:
                    conlist.append(str(d[0][i-1])+" "+str(d[0][i]))
                except:
                    conlist.append(str(d[0][i]))

In [39]:
hhhh=pd.DataFrame(conlist)
hhhh

                                                      0
0     황당하여라기분이 너무상하면서 화가나더라  제가 거지도아니고 쌀 한포대 얼마나한다고 ...
1     흑나눔 보내드리기로한거 이번주에 꼭 보내께여)박력분은없고마들렌은 굽고싶고 해서박력쌀...
2     마들렌도 첨인데쌀가루로 하려니 걱정이 앞섰지만맛없으면 내가먹겠다 하는 마음으로모카,...
3     )마지막판 구울때야 온도감잡아서제대로 배꼽이 올라온건 한판밖에 안되네요 첫째가 엄마...
4     오늘 밥먹다보니 사이사이에 숯 조각들이 보여서;; 숯은 그냥 빼야겠다 생각하고 숯조...
...                                                 ...
5974  저번주인가 주말에 할머니 댁 내려갔다가 동생이 쌀과자에 반해버려서 오는 길에 큰 거...
5975   사실 평소에 전 과자를 별로 안먹구 초콜릿이나 젤리같은 걸 먹는 거 같아여 과자 ...
5976                     쌀과자 냠냠 맛있게 먹으며 열심히 즐겁게 공부해봐요 💕
5977    *오늘의 최저가 정보롯데 백화점 납품 10kg 쌀등급 상두개 구매 개당 2370...
5978  쌀튀밥 두개 (유통기한 2020317)어그 130사이즈(사용감 잇네용)검정 운동화 ...

[5979 rows x 1 columns]

In [40]:
for i in range(len(hhhh)):
    hhhh[0][i]=hhhh[0][i].lstrip()
    hhhh[0][i]=hhhh[0][i].rstrip()

In [41]:
flv=hhhh.drop_duplicates([0],keep = 'first')
flv.to_excel("flv2.xlsx")
flv

                                                      0
0     황당하여라기분이 너무상하면서 화가나더라  제가 거지도아니고 쌀 한포대 얼마나한다고 ...
1     흑나눔 보내드리기로한거 이번주에 꼭 보내께여)박력분은없고마들렌은 굽고싶고 해서박력쌀...
2     마들렌도 첨인데쌀가루로 하려니 걱정이 앞섰지만맛없으면 내가먹겠다 하는 마음으로모카,...
3     )마지막판 구울때야 온도감잡아서제대로 배꼽이 올라온건 한판밖에 안되네요 첫째가 엄마...
4     오늘 밥먹다보니 사이사이에 숯 조각들이 보여서;; 숯은 그냥 빼야겠다 생각하고 숯조...
...                                                 ...
5974  저번주인가 주말에 할머니 댁 내려갔다가 동생이 쌀과자에 반해버려서 오는 길에 큰 거...
5975  사실 평소에 전 과자를 별로 안먹구 초콜릿이나 젤리같은 걸 먹는 거 같아여 과자 먹...
5976                     쌀과자 냠냠 맛있게 먹으며 열심히 즐겁게 공부해봐요 💕
5977  *오늘의 최저가 정보롯데 백화점 납품 10kg 쌀등급 상두개 구매 개당 23700원...
5978  쌀튀밥 두개 (유통기한 2020317)어그 130사이즈(사용감 잇네용)검정 운동화 ...

[5881 rows x 1 columns]

In [42]:
conlist=[]
for i in range(len(data2)):

    a=[]
    a.append(data2["content"][i].split("||-||"))
    
    d=pd.DataFrame(a).T
    d=d[d[0]!=""].reset_index()
    d=d[d[0]!="구요"].reset_index()
    conca1=d[d[0].str.contains("잡곡|찹쌀|현미|백미|보리|햅쌀|품종",na=False)]
    conidex=conca1.index
    list(conidex)


    for i in list(conidex):
        try:

             conlist.append(str(d[0][i-1])+" "+str(d[0][i])+" "+str(d[0][i+1]))

        except:
            try:
                conlist.append(str(d[0][i])+" "+str(d[0][i+1]))
            except:
                try:
                    conlist.append(str(d[0][i-1])+" "+str(d[0][i]))
                except:
                    conlist.append(str(d[0][i]))

In [43]:
iiii=pd.DataFrame(conlist)
iiii

                                                      0
0     처음와서는 일본품종쌀 주문해먹었었고그담엔 한국쌀먹었는데마트에서 한국아주머니께서 현지...
1     사진에는 잘 안보이는데 시골에서 보내주신 쌀 두 포대 오늘 뜯어보니 다 현미처럼 누...
2     평소 시골에서 보내주시는 쌀이 따로 있어서 먹지 못하고시간이 흘렀어요  사진에서 보...
3      몇일전에 쌀이 바닥나서 신랑 시댁 보내가쌀 좀 받아와야겠다 했거든요 (시엄니가 전...
4      쌀이유식은 중단했지만, 아가가 누나 먹는거에 너무 집중하고 먹고싶어해서 찐고구마를...
...                                                 ...
2029      친정해서 보내온 2019 햅쌀  판매해요 너무많이 보내셔서 ;; 보관도 힘들어서요
2030   잡초 사이에서 살아남기 위해 키를 키운 것 같아요  게다가 이게 가장 큰 품종도 ...
2031  이제 후기 시작 하는데여태까지 백미만 먹여본 게으른 엄마예요 후기 시작하면서 이제 ...
2032  후기 시작하면서 이제 좀 다양하게 먹일려고 하는데어떤 쌀종류 먹일수있는지 알려주세요...
2033               제가 알고있는건 현미 수수 정도네요 백미랑 섞여서 먹이는거 맞나요

[2034 rows x 1 columns]

In [44]:
for i in range(len(iiii)):
    iiii[0][i]=iiii[0][i].lstrip()
    iiii[0][i]=iiii[0][i].rstrip()

In [45]:
kind=iiii.drop_duplicates([0],keep = 'first')
kind.to_excel("kind2.xlsx")
kind

                                                      0
0     처음와서는 일본품종쌀 주문해먹었었고그담엔 한국쌀먹었는데마트에서 한국아주머니께서 현지...
1     사진에는 잘 안보이는데 시골에서 보내주신 쌀 두 포대 오늘 뜯어보니 다 현미처럼 누...
2     평소 시골에서 보내주시는 쌀이 따로 있어서 먹지 못하고시간이 흘렀어요  사진에서 보...
3     몇일전에 쌀이 바닥나서 신랑 시댁 보내가쌀 좀 받아와야겠다 했거든요 (시엄니가 전에...
4     쌀이유식은 중단했지만, 아가가 누나 먹는거에 너무 집중하고 먹고싶어해서 찐고구마를 ...
...                                                 ...
2029      친정해서 보내온 2019 햅쌀  판매해요 너무많이 보내셔서 ;; 보관도 힘들어서요
2030  잡초 사이에서 살아남기 위해 키를 키운 것 같아요  게다가 이게 가장 큰 품종도 아...
2031  이제 후기 시작 하는데여태까지 백미만 먹여본 게으른 엄마예요 후기 시작하면서 이제 ...
2032  후기 시작하면서 이제 좀 다양하게 먹일려고 하는데어떤 쌀종류 먹일수있는지 알려주세요...
2033               제가 알고있는건 현미 수수 정도네요 백미랑 섞여서 먹이는거 맞나요

[1994 rows x 1 columns]

In [46]:
conlist=[]
for i in range(len(data2)):

    a=[]
    a.append(data2["content"][i].split("||-||"))
    
    d=pd.DataFrame(a).T
    d=d[d[0]!=""].reset_index()
    d=d[d[0]!="구요"].reset_index()
    conca1=d[d[0].str.contains("배송|배달|택배|인터넷|마트|농협|포장",na=False)]
    conidex=conca1.index
    list(conidex)


    for i in list(conidex):
        try:

             conlist.append(str(d[0][i-1])+" "+str(d[0][i])+" "+str(d[0][i+1]))

        except:
            try:
                conlist.append(str(d[0][i])+" "+str(d[0][i+1]))
            except:
                try:
                    conlist.append(str(d[0][i-1])+" "+str(d[0][i]))
                except:
                    conlist.append(str(d[0][i]))

In [48]:
jjjj=pd.DataFrame(conlist)
jjjj

                                                      0
0     그리고 한번도 풍* 쌀은 이런적 없답니다  그래서 제가 쌀 처음 포장때부터 잘못된걸...
1     처음와서는 일본품종쌀 주문해먹었었고그담엔 한국쌀먹었는데마트에서 한국아주머니께서 현지...
2     쌀식빵은유화제나 방부제를 사용하지 않습니다 당일 드시기를 권해드리며택배로 받으실 경...
3      ☆☆오징어먹물쌀식빵 1+1 이벤트☆☆《《오징어먹물쌀식빵을 한개 구입하시면 다른 쌀...
4     )-참여방법1) 오징어먹물쌀식빵 주문은 오징어먹물쌀식빵 갯수, 요일, 수령방법을댓글...
...                                                 ...
2053  충주愛 퐁당 농촌체험여행 발효쌀찐빵만들기191130191201충주농촌체험여행쌀찐빵만...
2054    *오늘의 최저가 정보롯데 백화점 납품 10kg 쌀등급 상두개 구매 개당 2370...
2055    *오늘의 최저가 정보롯데 백화점 납품 10kg 쌀등급 상두개 구매 개당 2370...
2056  공유의 목적에 올리시는 것이니 글게시분은 부담 가지지 마시고 올려 주시기 바랍니다 ...
2057  여기 상품 올려 주시는분이랑 판매자랑은 아무연관이 없습니다 제품및 배송 문제점에 대...

[2058 rows x 1 columns]

In [49]:
for i in range(len(jjjj)):
    jjjj[0][i]=jjjj[0][i].lstrip()
    jjjj[0][i]=jjjj[0][i].rstrip()

In [50]:
chn=jjjj.drop_duplicates([0],keep = 'first')
chn.to_excel("chn2.xlsx")
chn

                                                      0
0     그리고 한번도 풍* 쌀은 이런적 없답니다  그래서 제가 쌀 처음 포장때부터 잘못된걸...
1     처음와서는 일본품종쌀 주문해먹었었고그담엔 한국쌀먹었는데마트에서 한국아주머니께서 현지...
2     쌀식빵은유화제나 방부제를 사용하지 않습니다 당일 드시기를 권해드리며택배로 받으실 경...
3     ☆☆오징어먹물쌀식빵 1+1 이벤트☆☆《《오징어먹물쌀식빵을 한개 구입하시면 다른 쌀식...
4     )-참여방법1) 오징어먹물쌀식빵 주문은 오징어먹물쌀식빵 갯수, 요일, 수령방법을댓글...
...                                                 ...
2053  충주愛 퐁당 농촌체험여행 발효쌀찐빵만들기191130191201충주농촌체험여행쌀찐빵만...
2054  *오늘의 최저가 정보롯데 백화점 납품 10kg 쌀등급 상두개 구매 개당 23700원...
2055  *오늘의 최저가 정보롯데 백화점 납품 10kg 쌀등급 상두개 구매 개당 23700원...
2056  공유의 목적에 올리시는 것이니 글게시분은 부담 가지지 마시고 올려 주시기 바랍니다 ...
2057  여기 상품 올려 주시는분이랑 판매자랑은 아무연관이 없습니다 제품및 배송 문제점에 대...

[2010 rows x 1 columns]